version: '3.2'
services:
  database_dev:
    container_name: "${DATABASE_NAME}"
    image: 'nusskylab2/postgres_plpgsql_check_pgtap'
    # build: # uncomment this only if you need to build image from scratch instead of pulling from DockerHub
    #   context: './helpers/dbutil'
    #   dockerfile: 'Dockerfile'
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './:/nusskylabx'
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
volumes:
  pgdata:
