name: CI
on: [push, pull_request]
jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-latest
    services:
      database:
        image: nusskylab2/postgres_plpgsql_check_pgtap
        env:
          POSTGRES_USER: pg
          POSTGRES_PASSWORD: pg
          POSTGRES_DB: skylab_devx
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Install go
      uses: actions/setup-go@v1
      with:
        go-version: '1.14.x'
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: go run cmd/loadsql/main.go -test
      run: go run cmd/loadsql/main.go -test
    - name: go test ./... -coverprofile=coverage.out
      run: go test ./... -coverprofile=coverage.out
    - name: npm ci && npx webpack
      run: npm ci && npx webpack
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
          infile: coverage.out
          outfile: coverage.lcov
    - name: Upload coverage.lcov to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
